### ISSUE TITLE
Indicate that cancelled builds need to be looked into

### ISSUE THREAD

**Issue by zmughal** [zmughal-github-actions/events-to-irc#1]

**Comment by mohawk2** [comment]
My aspiration is that the current "(tick) success (E cancelled)" be changed to "(cross) some cancelled" - a lack of red in the current setup caused me to miss a timeout on MacOS which actually fails when run.

**Comment by zmughal** [comment]
Ah, yes, this was from a time when a cancelled build meant re-running the whole
workflow. Now that it is possible to re-run a single part of the workflow, it
should be treated as a failure.

**Comment by mohawk2** [comment]
I'd argue that was always not quite correct - having timed-out jobs (shown in pale blue next to a green tick) isn't exactly a near miss for real success ;-)
